### ISSUE TITLE
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam' with 2080ti

### ISSUE THREAD

**Issue by SeekPoint** [dredwardhyde/gpt-neo-fine-tuning-example#16]
(gh_gpt-neo-fine-tuning-example) r730ub20@r730ub20-M0:~/llm_dev/gpt-neo-fine-tuning-example$ python3 gpt_neo_xl_deepspeed.py 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[2023-05-22 21:54:39,000] [INFO] [comm.py:622:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Max length: 62
[2023-05-22 21:55:12,297] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.9.2, git-hash=unknown, git-branch=unknown
[2023-05-22 21:55:12,388] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
Installed CUDA version 11.7 does not match the version torch was compiled with 11.3 but since the APIs are compatible, accepting this combination
Installed CUDA version 11.7 does not match the version torch was compiled with 11.3 but since the APIs are compatible, accepting this combination
Using /home/r730ub20/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Traceback (most recent call last):
  File "gpt_neo_xl_deepspeed.py", line 46, in <module>
    Trainer(model=model, args=training_args, train_dataset=train_dataset,
  File "/home/r730ub20/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1112, in train
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/home/r730ub20/.local/lib/python3.8/site-packages/transformers/deepspeed.py", line 355, in deepspeed_init
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/home/r730ub20/.local/lib/python3.8/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/r730ub20/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 308, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/r730ub20/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1162, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/r730ub20/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1218, in _configure_basic_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/home/r730ub20/.local/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/home/r730ub20/.local/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 445, in load
    return self.jit_load(verbose)
  File "/home/r730ub20/.local/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 480, in jit_load
    op_module = load(name=self.name,
  File "/home/r730ub20/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/home/r730ub20/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1337, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/r730ub20/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1418, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "/home/r730ub20/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1474, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f97b8a353a0>
Traceback (most recent call last):
  File "/home/r730ub20/.local/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

**Comment by tallesairan** [comment]
me too :(
